query_motor_node:
  ros__parameters:
    serial_port: /dev/ttyACM0
    serial_baudrate: 921600
    can_bitrate_index: 0
    set_can_bitrate_on_start: true

    motor_ids: [1, 2, 3, 4]
    master_id: 0
    accept_any_master_id: true
    log_rx_frames: false
    probe_attempts: 3
    probe_timeout_s: 0.2
    probe_gap_s: 0.03
    usbcan_send_cmd: 1
